export const COLORS = {
  BADGE_BACKGROUND_COLOR: '#186200',
};

export const CURRENCIES = [
  { code: 'USD', title: 'United States Dollar' },
  { code: 'BRL', title: 'Brazilian Real' },
  { code: 'AED', title: 'United Arab Emirates Dirham' },
  { code: 'AUD', title: 'Australian Dollar' },
  { code: 'BHD', title: 'Bahraini Dinar' },
  { code: 'BOB', title: 'Bolivian Boliviano' },
  { code: 'CAD', title: 'Canadian Dollar' },
  { code: 'COP', title: 'Colombian Peso' },
  { code: 'CZK', title: 'Czech Koruna' },
  { code: 'DKK', title: 'Danish Krone' },
  { code: 'EGP', title: 'Egyptian Pound' },
  { code: 'EUR', title: 'Euro' },
  { code: 'GBP', title: 'Pound Sterling' },
  { code: 'HKD', title: 'Hong Kong Dollar' },
  { code: 'IDR', title: 'Indonesian Rupiah' },
  { code: 'ILS', title: 'Israeli New Shekel' },
  { code: 'INR', title: 'Indian Rupee' },
  { code: 'ISK', title: 'Icelandic Króna' },
  { code: 'JMD', title: 'Jamaican Dollar' },
  { code: 'JOD', title: 'Jordanian Dinar' },
  { code: 'JPY', title: 'Japanese Yen' },
  { code: 'KES', title: 'Kenyan Shilling' },
  { code: 'LBP', title: 'Lebanese pound' },
  { code: 'LKR', title: 'Sri Lankan Rupee' },
  { code: 'MAD', title: 'Moroccan Dirham' },
  { code: 'MXN', title: 'Mexican Peso' },
  { code: 'MYR', title: 'Malaysian Ringgit' },
  { code: 'NAD', title: 'Namibian Dollar' },
  { code: 'NOK', title: 'Norwegian Krone' },
  { code: 'NPR', title: 'Nepalese Rupee' },
  { code: 'NZD', title: 'New Zealand Dollar' },
  { code: 'PHP', title: 'Philippine Peso' },
  { code: 'PKR', title: 'Pakistani Rupee' },
  { code: 'PLN', title: 'Polish Zloty' },
  { code: 'QAR', title: 'Qatari Rial' },
  { code: 'RON', title: 'Romanian Leu' },
  { code: 'RUB', title: 'Russian Ruble' },
  { code: 'SEK', title: 'Swedish Krona' },
  { code: 'SGD', title: 'Singapore Dollar' },
  { code: 'THB', title: 'Thai Baht' },
  { code: 'TRY', title: 'Turkish lira' },
  { code: 'TWD', title: 'New Taiwan dollar' },
  { code: 'VEF', title: 'Sovereign Bolivar' },
  { code: 'XCD', title: 'East Caribbean Dollar' },
  { code: 'XOF', title: 'West African CFA franc' },
  { code: 'ZAR', title: 'South African Rand' },
];
